name: Job Outputs Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # このジョブからの出力を定義
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.date }}
      matrix-result: ${{ steps.matrix-output.outputs.matrix_json }}

    steps:
      - name: Set output value
        id: step1
        run: echo "test=hello-from-job1" >> $GITHUB_OUTPUT

      - name: Set date output
        id: step2
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create matrix data for next job
        id: matrix-output
        run: echo "matrix_json={\"include\":[{\"fruit\":\"apple\",\"color\":\"red\"},{\"fruit\":\"banana\",\"color\":\"yellow\"}]}" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - name: Set different output
        id: step1
        run: echo "test=hello-from-job2" >> $GITHUB_OUTPUT

  job3:
    # job1とjob2の両方が完了するのを待つ
    needs: [job1, job2]
    runs-on: ubuntu-latest

    steps:
      - name: Use outputs from job1 and job2
        run: |
          echo "From job1: ${{ needs.job1.outputs.output1 }}"
          echo "Date from job1: ${{ needs.job1.outputs.output2 }}"
          echo "From job2: ${{ needs.job2.outputs.output1 }}"

      - name: Debug matrix output
        run: echo "${{ needs.job1.outputs.matrix-result }}"
